python3 ../../../main_pretrain.py \
    --dataset $1 \
    --backbone resnet18 \
    --data_dir ./datasets \
    --max_epochs 800 \
    --gpus 0 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 1.0 \
    --classifier_lr 0.1 \
    --weight_decay 1e-5 \
    --batch_size 1024 \
    --num_workers 4 \
    --crop_size 32 \
    --brightness 0.8 \
    --contrast 0.8 \
    --saturation 0.8 \
    --hue 0.2 \
    --gaussian_prob 0.0 0.0 \
    --crop_size 32 \
    --num_crops_per_aug 1 1 \
    --name simclr-$1-momentum99-800 \
    --wandb_version simclr-$1-momentum99-800 \
    --project ssl-project \
    --entity cu-ssl-project \
    --save_checkpoint \
    --method simclrmom \
    --temperature 0.4 \
    --proj_hidden_dim 2048 \
    --proj_output_dim 256 \
    --base_tau_momentum 0.99 \
    --final_tau_momentum 0.99 \
    --momentum_classifier \
    --wandb \
#    --checkpoint_dir "trained_models/simclrmom/simclr-cifar100-momentum56" \
#    --resume_from_checkpoint "trained_models/simclrmom/simclr-cifar100-momentum56/simclr-cifar100-momentum56-simclr-cifar100-momentum56-ep=126.ckpt" \
